### ISSUE TITLE
誤記

### ISSUE THREAD

**Issue by antarcticlion** [tendai22/mame-sbc#1]
翻訳を入れたまま表示されたものを見誤ってしまいました。キャンセルしてください。m(_ _)m

**Comment by antarcticlion** [comment]
翻訳を入れたまま表示されたものを見誤ってしまいました。キャンセルしてください。m(_ _)m

**Comment by tendai22** [comment]
了解しました。とりあえず誤記・要訂正項目はなかったということで。
チェックとご連絡ありがとうございました。
